// LOCALHOST

###localhost
GET http://localhost:3000


###published link on render.com
https://web-app-project1.onrender.com/

###Get all contacts
GET http://localhost:3000/test

###Get one contact
GET http://localhost:3000/test/6676c2c73fb09bc863eaaee8

###Post request, add an item
POST http://localhost:3000 HTTP/1.1
Content-Type: application/json

{
  }

###Update an item, put request
PUT http://localhost:3000/test/6676c6688af61d8a6267c94b HTTP/1.1
Content-Type: application/json

{
  }

###Delete request
DELETE http://localhost:3000/test/6676c6688af61d8a6267c94b HTTP/1.1
